"use client"

import type { Metadata } from 'next'
import './globals.css'

import { Montserrat } from 'next/font/google';
import { createClient } from '@supabase/supabase-js'



const montserrat = Montserrat({
  weight: ['300', '400', '500', '700'],
  subsets: [ "cyrillic", "cyrillic-ext", 'latin'],
  display:'swap',
  fallback: ['Arial', 'sans-serif'],
});

// export const metadata = {
//   title: 'Ganzh_mua',
//   description: 'Generated by create next app',
// }
const supabaseUrl = 'https://knyyollnxptsniojscia.supabase.co'
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

export const supabase: any = createClient(supabaseUrl, `${supabaseKey}`)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
